api_version: 1
runtime: python38
threadsafe: true
instance_class: B4_1G
#entrypoint: gunicorn -b :$PORT main:app
#entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 2 --threads 4

